#!/bin/sh
set -e

HERE="$(dirname "$(readlink -f "$0")")"

export APPDIR="$HERE"
export PATH="$HERE/usr/bin:${PATH:-}"
export LD_LIBRARY_PATH="$APPDIR/usr/bin:${LD_LIBRARY_PATH:-}"

exec "$HERE/usr/bin/gtkornell" "$@"